[config]
version_check = false

# [config.wallpaper]
# command = "swww"
# arguments = ["img", "--transition-type", "center"]
# set = true

[templates.quickshell]
input_path = "./quickshell.json"
output_path = "~/.config/quickshell/settings/colours.json"

[templates.ags]
input_path = "./ags"
output_path = "./../ags/style/colors.scss"

[templates.foot]
input_path = "./foot-color.ini"
output_path = "./../foot/foot-color.ini"

[templates.hypr]
input_path = "./hyprland-color.conf"
output_path = "./../hypr/hyprland-color.conf"
post_hook = 'hyprctl reload'
